project:
  type: book

book:
  title: "Quantifying the Flow of Information"
  site-url: "https://manuel-rhdt.github.io/webthesis/"
  author: "Manuel Reinhardt"
  date: "2025-06-13"
  repo-url: https://github.com/manuel-rhdt/webthesis
  downloads: [pdf]
  chapters:
    - index.qmd
    - 01-introduction.md
    - 02-path-weight-sampling.md
    - 03-variants.md
    - 04-chemotaxis.md
    - 05-gaussian.md
    - 06-mlpws.md
    - appendix.md
    - part: "Endmatter"
      chapters:
      - summary.md
      - publications.md
      - acknowledgments.md
      - about-the-author.md

bibliography: references.bib

numbering: true

format:
  html:
    theme:
      - cosmo
      - brand
    html-math-method: mathml

filters:
  - quarto
  - author-numeric.lua
