project:
  type: book

book:
  title: "Quantifying the Flow of Information"
  site-url: "https://manuel-rhdt.github.io/webthesis/"
  author: "Manuel Reinhardt"
  date: "2025-06-13"
  repo-url: https://github.com/manuel-rhdt/webthesis
  downloads: [pdf]
  chapters:
    - index.qmd
    - chapters/01-introduction.md
    - chapters/02-path-weight-sampling.md
    - chapters/03-variants.md
    - chapters/04-chemotaxis.md
    - chapters/05-gaussian.md
    - chapters/06-mlpws.md
    - chapters/appendix.md
    - part: "Endmatter"
      chapters:
      - chapters/summary.md
      - chapters/publications.md
      - chapters/acknowledgments.md
      - chapters/about-the-author.md

bibliography: references.bib

numbering: true

format:
  html:
    theme:
      - cosmo
      - brand
    html-math-method: mathml

filters:
  - quarto
  - author-numeric.lua
